### PR TITLE
Insert select

### PR DESCRIPTION
**Pull request by laderast**
I added the the select and insert tag features discussed in #18 . 

Note that this requires the more recent update of `shinyAce` than is on cran. I had to PR a bug fix for the selection part of `shinyAce` - so you will have to `install_github("trestletech/shinyAce")` before you can run this.

### CODE REVIEW

**Comment by elinw** [comment]
@laderast I'm sorry, I lost track of this, but I'm going to see if I can solve the conflicts.

**Comment by elinw** [comment]
Hi,

https://github.com/ropenscilabs/qcoder/pull/46  is an update of this, but with no conflicts and fixing a bunch of other broken things (not really sure what happened there ...).
Two issues I noticed that if you could think about, it would be great.  
First, if you try to insert a code with no text selected the app crashes, so there should probably be a check for that and then a warning.
Second if you insert a new code the code is just {#}  .. I guess ideally it would add the new code? Otherwise it would be good to not add anything and give a message.

**Comment by laderast** [comment]
@elinw - thanks for the feedback and suggestions - I will try and fix these soon.

**Comment by elinw** [comment]
Oh I forgot that also one of your tests was failing and I commented it out, but we should look at why that was.

**Comment by elinw** [comment]
@laderast this is closing because I merged the other branch that was created from this one.

**Comment by laderast** [comment]
@elinw - sorry I didn't get to these this weekend - I will work on fixing the bugs

**Pull request merged**
