### PR TITLE
Table outputs to datatable as suggested in issue #37

### PR DESCRIPTION
**Pull request by FrdVnW**
I have this proposal for the reactive tables, using DT

### CODE REVIEW

**Comment by elinw** [comment]
The reason I didn't do this before is that I was thinking about some tables being editable, but we could always look at that later.

**Comment by elinw** [comment]
This is great but we need to add datatable to the imports list in DESCRIPTION file and also add you as a contributor.  Do you want to do that?

**Comment by FrdVnW** [comment]
Thank you, sure I accept your invitation ;-). Ok for the DESCRIPTION file, also, I forgot this part

**Comment by FrdVnW** [comment]
Is there a way to chat/exchange for new development, or all is via github/issue/pull request. 
I have ideas and I did some of them yesterday, maybe

**Comment by elinw** [comment]
Right now we're mainly in git hub but if you want to email me that's fine.

**Pull request merged**
