### PR TITLE
Start to add tests, some refactoring.

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by learithe** [comment]
Hi Elin, I'm not sure if there's a formal way to respond to a 'request for review'? The refactoring looks good to me, makes heaps of sense. I made a minor edit to the error check function to replace the loop with sapply(); the commit is on my fork, doesn't seem big enough change to bother with a pull request here yet though.

**Comment by elinw** [comment]
Thanks! Just a comment is fine.   No, by all means small PRs are actually easier to manage and track if you ever have to go back through history to figure out what you were doing.  Great to switch ti to sapply, to me as much as possibly we should be refactoring the loops to either use *apply or purrr or something from dplyr.  I’d favor moving some more pieces out to functions both to facilitate that and to make unit testing easier. 

Elin

**Comment by learithe** [comment]
One question though -- you removed the reference to the document number on the warning message when you encounter a document with no codes. What was the reasoning for this? Seems like a useful thing to have in the error message if you're processing multiple documents at once?

**Comment by elinw** [comment]
Oh because we actually don’t have access to it in the separate function.  But I think that since this is now also running on saving an individual document people will be in the UI  with the document open when they get the message.  We could also try to come up with a way to retrieve it.

We need to figure out how to put the warning display into the app instead of having it display in the console … 

Elin

**Comment by learithe** [comment]
Ah. I have yet to figure out how to run the full app, so I don't have the full user experience yet!  Getting there slowly, today I learned about testthat! I iz noob -- lots to learn, this has been great for me in that regard! 😄

**Comment by elinw** [comment]
Oh, look in the read me, create a project with the sample data, then read in the data, then qcode().  Three quick steps.

I just pushed up a branch with code for taking the newly found codes and adding them to the codes data frame.  You'll see it's a bit awkward because I had to really embed it in the parser in order to get the list of codes. It would be cleaner if I could make it work the way the error check does, which is on a single document (and then can be iterated over all the documents).  I  tried to write it in a way that would make refactoring not too painful.

**Comment by learithe** [comment]
I just hadn't had time to try it.  I'm not sure why getting the list of codes from the function is an issue, seems like you could just pull the code column from the returned data frame and run unique() on it? Or am I missing something?

**Comment by elinw** [comment]
I’m talking about new codes that have been entered in the text but are not in the code file (the parse function doesn’t and shouldn’t update the code file) and we want it from just one file (though I could run the full parse of the whole data set  on every save that seems inefficient.  Anyway it turned out to be a pretty simple function.

**Pull request merged**
