### PR TITLE
bug in read code file. Now import_data is ok without a codes.csv

### PR DESCRIPTION
**Pull request by FrdVnW**

### CODE REVIEW

**Comment by elinw** [comment]
I'm pretty sure if you don't give it the full path it is going to end up in unexpected locations.  Again, remember that users will not always be in the UI and may not want to have the file stored in their current working directory.

**Comment by FrdVnW** [comment]
Ok sorry, you are right, it is surely link to my config, my manner to lauch qcoder. The variable definition confused me in the function project_name / project_path.

**Comment by FrdVnW** [comment]
but take a look to the commit, because I use also full path for project path. The variable 'project name' of create_empty... require the project name, and not the project path (another variable is there for that)

**Comment by elinw** [comment]
Yes this function is really complicated depending on which combination of parameters is supplied, and I agree it doesn't work in all combinations.  I started writing some tests for this; that will help clean up the logic.  Possibly we should really simplify it.

**Comment by FrdVnW** [comment]
yes you are right. I am not aware about 'test', I have to learn that part (rigth now). What I pointed in these two functions : the create_empty_code has no output. That is not a problem per se. But the function 'read' (if no file) try to get an output from the create_empty_code.
A second point, for working with full flexibility : 'import project' does not have a 'project path' variable

**Comment by FrdVnW** [comment]
the PR is a kind of work around, rapid hack of the two function, but not working in all situations

**Comment by elinw** [comment]
So I did some rewriting and added tests. https://github.com/ropenscilabs/qcoder/pull/81  
It's really a lot of "if" blocks but at least it just runs once in the app.

**Comment by elinw** [comment]
This issue of the build failing is very annoying because I believe it has nothing to do with the code at all.  I'm trying to find a solution.

**Pull request merged**
